
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ASSIGN BLOCK DICT EXPORT FLOAT ID INT LIST LONG LPAREN MINE NUMBER PRINT RPAREN RUN SEPARATOR STR STRING TUPLE TYPEASSIGN VIEWstart : block_definition block_operationsblock_definition : BLOCK ID ASSIGN LPAREN attributes RPARENblock_operations : block_operationblock_operations : block_operations block_operationblock_operation : ADD ID ASSIGN LPAREN new_atts RPARENblock_operation : PRINT IDblock_operation : RUN IDblock_operation : MINE IDblock_operation : EXPORT IDblock_operation : VIEW IDtype : STR\n| INT\n| LONG\n| FLOAT\n| LIST\n| TUPLE\n| DICTattribute : ID TYPEASSIGN typeattributes : attributeattributes : attributes SEPARATOR attributenew_att : ID TYPEASSIGN STRINGnew_att : ID TYPEASSIGN NUMBERnew_atts : new_attnew_atts : new_atts SEPARATOR new_att'
    
_lr_action_items = {'BLOCK':([0,],[3,]),'$end':([1,4,5,13,15,16,17,18,19,34,],[0,-1,-3,-4,-6,-7,-8,-9,-10,-5,]),'ADD':([2,4,5,13,15,16,17,18,19,31,34,],[6,6,-3,-4,-6,-7,-8,-9,-10,-2,-5,]),'PRINT':([2,4,5,13,15,16,17,18,19,31,34,],[7,7,-3,-4,-6,-7,-8,-9,-10,-2,-5,]),'RUN':([2,4,5,13,15,16,17,18,19,31,34,],[8,8,-3,-4,-6,-7,-8,-9,-10,-2,-5,]),'MINE':([2,4,5,13,15,16,17,18,19,31,34,],[9,9,-3,-4,-6,-7,-8,-9,-10,-2,-5,]),'EXPORT':([2,4,5,13,15,16,17,18,19,31,34,],[10,10,-3,-4,-6,-7,-8,-9,-10,-2,-5,]),'VIEW':([2,4,5,13,15,16,17,18,19,31,34,],[11,11,-3,-4,-6,-7,-8,-9,-10,-2,-5,]),'ID':([3,6,7,8,9,10,11,22,23,32,35,],[12,14,15,16,17,18,19,24,27,24,27,]),'ASSIGN':([12,14,],[20,21,]),'LPAREN':([20,21,],[22,23,]),'TYPEASSIGN':([24,27,],[30,33,]),'RPAREN':([25,26,28,29,36,37,38,39,40,41,42,43,44,45,46,47,],[31,-19,34,-23,-18,-11,-12,-13,-14,-15,-16,-17,-20,-21,-22,-24,]),'SEPARATOR':([25,26,28,29,36,37,38,39,40,41,42,43,44,45,46,47,],[32,-19,35,-23,-18,-11,-12,-13,-14,-15,-16,-17,-20,-21,-22,-24,]),'STR':([30,],[37,]),'INT':([30,],[38,]),'LONG':([30,],[39,]),'FLOAT':([30,],[40,]),'LIST':([30,],[41,]),'TUPLE':([30,],[42,]),'DICT':([30,],[43,]),'STRING':([33,],[45,]),'NUMBER':([33,],[46,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'block_definition':([0,],[2,]),'block_operations':([2,],[4,]),'block_operation':([2,4,],[5,13,]),'attributes':([22,],[25,]),'attribute':([22,32,],[26,44,]),'new_atts':([23,],[28,]),'new_att':([23,35,],[29,47,]),'type':([30,],[36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> block_definition block_operations','start',2,'p_start','main.py',249),
  ('block_definition -> BLOCK ID ASSIGN LPAREN attributes RPAREN','block_definition',6,'p_block_definition','main.py',254),
  ('block_operations -> block_operation','block_operations',1,'p_block_operations_single','main.py',271),
  ('block_operations -> block_operations block_operation','block_operations',2,'p_block_operations_multiple','main.py',275),
  ('block_operation -> ADD ID ASSIGN LPAREN new_atts RPAREN','block_operation',6,'p_block_operation_add','main.py',280),
  ('block_operation -> PRINT ID','block_operation',2,'p_block_operation_print','main.py',299),
  ('block_operation -> RUN ID','block_operation',2,'p_block_operation_run','main.py',312),
  ('block_operation -> MINE ID','block_operation',2,'p_block_operation_mine','main.py',342),
  ('block_operation -> EXPORT ID','block_operation',2,'p_block_operation_export','main.py',360),
  ('block_operation -> VIEW ID','block_operation',2,'p_block_operation_view','main.py',378),
  ('type -> STR','type',1,'p_type','main.py',393),
  ('type -> INT','type',1,'p_type','main.py',394),
  ('type -> LONG','type',1,'p_type','main.py',395),
  ('type -> FLOAT','type',1,'p_type','main.py',396),
  ('type -> LIST','type',1,'p_type','main.py',397),
  ('type -> TUPLE','type',1,'p_type','main.py',398),
  ('type -> DICT','type',1,'p_type','main.py',399),
  ('attribute -> ID TYPEASSIGN type','attribute',3,'p_attribute','main.py',404),
  ('attributes -> attribute','attributes',1,'p_attributes_single','main.py',409),
  ('attributes -> attributes SEPARATOR attribute','attributes',3,'p_attributes_multiple','main.py',413),
  ('new_att -> ID TYPEASSIGN STRING','new_att',3,'p_new_att_string','main.py',419),
  ('new_att -> ID TYPEASSIGN NUMBER','new_att',3,'p_new_att_number','main.py',423),
  ('new_atts -> new_att','new_atts',1,'p_new_atts_single','main.py',428),
  ('new_atts -> new_atts SEPARATOR new_att','new_atts',3,'p_new_atts_multiple','main.py',432),
]
